### PR TITLE
Fix Quick Match cancel button not responding

### LINKED ISSUE #670: [Bug] Cancel button is unresponsive during "Quick Match" loading screen
### 🐛 Describe the bug

When attempting to find a Quick Match in Pair Chat, the loading screen appears. The "Cancel" button at the bottom of the screen does not respond to taps, making it impossible to abort the search without force-closing the app.

Steps to Reproduce

Open the Resonate app.

Navigate to the Pair Chat section.

Select "Anonymous" and click Quick Match.

While the "Hang on, Good things take time" loader is spinning, tap the Cancel button.

Expected Behavior The search should stop, and the user should be returned to the previous Pair Chat menu.

Actual Behavior The button shows no visual feedback and the loading screen persists.

Environment

Device: Samsung A56

OS: Android 16

App Version: 2.0.0
Updated on 17 Sept 2025

https://github.com/user-attachments/assets/fbd44c1c-3c78-4a8b-b6d1-a93ffc932260

### PR DESCRIPTION
**Pull request by Rozerxshashank**
## 🐛 Bug
The Cancel button in Quick Match could be tapped before the pairing request
was fully created, leading to a null-assertion crash and causing the UI
to get stuck on the loading screen.

## ✅ Fix
- Guarded against null `requestDocId`
- Safely closed realtime subscriptions
- Ensured navigation always occurs via a `finally` block

## 🧪 Testing
- Verified logic-level fix for the race condition
- Cancel action now always exits pairing screen safely
- Google Sign-In could not be tested locally due to Appwrite OAuth configuration

Fixes #670 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved request cancellation reliability: safer error handling during cancellation, conditional cleanup to avoid invalid operations, ensured subscriptions are closed reliably, and guaranteed navigation back to the main view after cancellation.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

**Comment by Rozerxshashank** [comment]
Hi @M4dhav  👋  
I’ve opened a PR that fixes this issue.  
Looking forward to your review. Thanks!

**Comment by M4dhav** [comment]
Please fix merge conflicts

**Review by M4dhav — CHANGES_REQUESTED** [review]
fix tests failure

File: lib/controllers/pair_chat_controller.dart [hunk 1]
```diff
@@ -238,17 +238,26 @@ class PairChatController extends GetxController {
...
+  try {
+    if (requestDocId != null) {
+      await tablesDB.deleteRow(
+        databaseId: masterDatabaseId,
+        tableId: pairRequestTableId,
+        rowId: requestDocId!,
+      );
+    }
+
+    requestDocId = null;
```
Comment (M4dhav) [inline lib/controllers/pair_chat_controller.dart:251]: Why set the requestDocId to null?

**Review by M4dhav — CHANGES_REQUESTED** [review]

File: lib/controllers/pair_chat_controller.dart (hunk 1 above)
Comment (Rozerxshashank) [reply lib/controllers/pair_chat_controller.dart:251]: I set to null beacuse if app keeps the old requestDocId it may try to cancel the same request again. (Like when button tapped twice)
It just avoids accidental reuse of an invalid ID and reset the controlller to a complete clean state.

Comment (M4dhav) [reply lib/controllers/pair_chat_controller.dart:251]: Great idea!

**Review by M4dhav — APPROVED** [review]
Great work, thank you for the contribution. 

Could you share a video of the functionality with this fix please?

**Comment by M4dhav** [comment]
@coderabbitai review

**Comment by Rozerxshashank** [comment]
https://github.com/user-attachments/assets/484588e3-7800-4d37-a0a2-e56e9b74e239
@M4dhav 
This is the video of the cancel button functionally working.

**Comment by M4dhav** [comment]
Merging, Thanks!
